CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE COMENTARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(200) NOT NULL,
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);